mailhoo:
  smtp.port: 1025
  web.allowed-origins:

spring:
  datasource:
    url: jdbc:h2:mem:mailhoo
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
server:
  error:
    whitelabel:
      enabled: false
