mailhoo:
  port: 1025

spring:
  datasource:
    url: jdbc:h2:mem:mailhoo
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    whitelabel:
      enabled: false
