mailhoo:
  smtp.port: 1025
  web.allowed-origins:
  data.jpa.table-name-prefix:
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:mailhoo
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.yo1000.mailhoo.infrastructure.TableNameStrategy
    properties:
      hibernate:
        default_batch_fetch_size: 1000
server:
  error:
    whitelabel:
      enabled: false
